### ISSUE TITLE
[Question] GitLab repository not onboarded

### ISSUE THREAD

**Issue by jeromelachaud** [renovatebot/app-support#1]
### Which Renovate are you using? CLI, App, or Pro
App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab

### Have you checked the logs? Don't forget to include them if relevant

I don't have any logs so far

### What is your question?
Hi there. 
I'd like to trigger the an onboarding PR but I have got this 404 error while trying to activate a repo from the renovatebot app for GitLab
https://v1.renovateapi.com/gitlab/repos/11936890/webhooks
I have pushed a barbone `renovate.json` file on the main branch with the following content : 
```
{
  "extends": [
    "config:base"
  ]
}
```
Is there anything that I've missed so far?
Thanks for helping out

**Comment by jeromelachaud** [comment]
the repository name is `insight`

**Comment by rarkins** [comment]
This repo was set to status=disabled so it wasn't getting queued hourly. I've manually changed it to enabled so you should see it serviced within the next 2-3 hours maximum.

**Comment by jeromelachaud** [comment]
Awesome 🎉, I keep my eyes on it and will update the issue accordingly.

**Comment by jeromelachaud** [comment]
Looks all good now. Thanks a lot! ❤️
