### ISSUE TITLE
Renovate Dashboard Job Logs Missing

### ISSUE THREAD

**Issue by esetnik** [renovatebot/app-support#10]
**What Renovate type are you using?**
Renovate dashboard https://app.renovatebot.com/dashboard with gitlab

**Describe the bug**
All job logs for all projects are missing. My setup has been working perfectly for months and I haven't changed anything.

**Did you see anything helpful in debug logs?**
I can't see any job logs anymore. The API returns an empty array for job logs on all projects.
```json
{"jobs":[]}
```

**To Reproduce**
1.  Login to app.renovatebot.com/dashboard

**Expected behavior**
Job logs should be visible and showing the history of jobs.

**Screenshots**

**Additional context**

**Comment by rarkins** [comment]
This is now resolved, thanks for raising the issue. Some GitLab accounts had been mistakenly flagged as disabled and so were not being serviced. I unflagged those affected and they've now all run and should continue running.

**Comment by esetnik** [comment]
@rarkins thanks for getting it sorted out. Renovate looks to be working again for me. Extend my thanks to the renovate team for building a great project.
