### ISSUE TITLE
renovate-bot failed to propose google-cloud-shared-dependencies update in 2 repos

### ISSUE THREAD

**Issue by stephaniewang526** [renovatebot/app-support#100]
We had to make below manual updates ourselves since renovate-bot did not propose these updates:

googleapis/java-webrisk#277
googleapis/java-translate#344

com.google.cloud:google-cloud-shared-dependencies `v0.14.1` and `v0.15.0` were both missed in the above two repos. However, we did get renovate-bot updates in our other 70+ Google-provided repos.

Could you investigate and let us know why the bot did not work?

Thank you!
(related to point 4 in [this comment](https://github.com/googleapis/java-cloud-bom/issues/735#issuecomment-729178463))

cc @chingor

**Comment by rarkins** [comment]
Also, I noticed other googleapis repos were in a similar state (installed but disabled) so I've reset them all so that they get enqueued in the next hourly scheduled runs.

**Comment by stephaniewang526** [comment]
Thank you for looking into this!
