### ISSUE TITLE
Remove waste of ugly logo space from pull requests

### ISSUE THREAD

**Issue by frenck** [renovatebot/app-support#101]
**What would you like Renovate to be able to do?**

![image](https://user-images.githubusercontent.com/195327/99678317-f897b280-2a7a-11eb-8b20-156a15fe26f7.png)

☝️ What the heck of fugly yellow garbage has been added to the PRs?
I don't want to have that. 

**Did you already have any implementation ideas?**

Dependabot here I come!

**Comment by rarkins** [comment]
It's controlled by the [prHeader](https://docs.renovatebot.com/configuration-options/#prheader) field.

```json
{
  "prHeader": null
}
```

**Comment by frenck** [comment]
I think we need to re-open the issue in that case, as according to the linked documentation is null by default:

![image](https://user-images.githubusercontent.com/195327/100516822-db539a00-3186-11eb-8531-b86caa9c5d38.png)
 

So this is either a bug or a documentation error. Should I file a new issue?
