### ISSUE TITLE
Renovate not working for Gitlab.com

### ISSUE THREAD

**Issue by puka-tchou** [renovatebot/app-support#105]
**Which Renovate are you using?**

WhiteSource Renovate App

**Which platform are you using?**

GitLab.com

**Have you checked the logs? Don't forget to include them if relevant**

I can't acces the logs, they do not load. (https://app.renovatebot.com/dashboard#gitlab/gaspacchio/back-to-the-future/)

**What would you like to do?**

What can I do to enable Renovate again?

**Comment by rarkins** [comment]
Sorry, please see #103
