### ISSUE TITLE
Re-activation of hosted WhiteSource Renovate App for gitlab.com

### ISSUE THREAD

**Issue by rarkins** [renovatebot/app-support#106]
The app for gitlab.com is indefinitely off-line as mentioned here: https://docs.renovatebot.com/install-gitlab-app/

In short, it's because malicious users could invite Renovate into their project and leverage the fact that pipelines in GitLab run with the credentials of the account that triggered CI to:

- spam published packages into any other public projects using Renovate that they can find
- git clone *private* projects of other Renovate users, if they had some way to learn or guess what those project names are

The app could be re-enabled under one of several circumstances:
- If we decide that running the bot with "skip-ci" forced on every commit is still useful (you'd get MRs, but your CI would be intentionally skipped)
- If GitLab change the security model of `CI_JOB_TOKEN` to be scoped only to the Project it runs in
- If GitLab add a first-class app/bot concept like is present on github.com

I will leave this issue open until either a solution is arrived at or we decided against all of the above being feasible, so please subscribe to it if you're interested to hear updates.

**Comment by HonkingGoose** [comment]
@rarkins, you might want to change the PR title, there's a typo. 😉 
`Re-actication` ->`Re-activation`

**Comment by yangm97** [comment]
Gitlab 13.5 added Project Scoped tokens https://gitlab.com/groups/gitlab-org/-/epics/2587

Gitlab 13.11 added group wide Oauth application support https://docs.gitlab.com/ee/integration/oauth_provider.html#group-owned-applications

Does it look like either of these would suffice?

**Comment by rarkins** [comment]
Before we check if their security model is satisfactory, are they supported on all gitlab.com plans?

**Comment by mbrodala** [comment]
[Group level apps](https://docs.gitlab.com/ee/integration/oauth_provider.html#group-owned-applications) are available for everyone in every tier.

But [project access tokens](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html) are currently not available in the free tier of gitlab.com:

![image](https://user-images.githubusercontent.com/5037116/117616632-a737c880-b16b-11eb-9e50-9169146d11ba.png)

**Comment by rarkins** [comment]
Group-level apps appear to be just a way to do private OAuth apps and does not support "bot" semantics,  unless I misunderstand it. If we were to switch to an OAuth approach (meaning "the bot" doesn't make MRs as itself, it makes them as you the end user) then does it present any advantage over an instance-wide OAuth app?

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place.

**Comment by jusurb** [comment]
@rarkins where is this one place you're having conversations in?

**Comment by rarkins** [comment]
https://github.com/renovatebot/renovate/discussions
