### ISSUE TITLE
GitHub App not working anymore

### ISSUE THREAD

**Issue by cfra** [renovatebot/app-support#109]
**What Renovate type, platform and version are you using?**

We are using the GitHub App

**Describe the bug**

I feel like we are probably doing something wrong, but I don't know what. Renovate seems to have stopped running for all of our repositories.

The last updates I can see are from December 22nd.

In the dashboard, I can see repositories, but none show any runs.

**Relevant debug logs**

I cannot find any debug logs, as the app seems to have stopped being run.

**Have you created a minimal reproduction repository?**

One of the public affected repositories is this one: https://github.com/picturepipe/renovate-config

**Comment by rarkins** [comment]
Each of the repos is showing up as uninstalled. I'll try to debug on our backend but can you also check that the app wasn't paused/revoked by someone on your team over Christmas?

**Comment by cfra** [comment]
I have double checked with the team and no one has touched any configuration of the Renovate GitHub App recently.

Before opening this issue I navigated to _Organization Settings_ -> _Installed GitHub Apps_ -> _Renovate_  and verified that the permissions for all repositories are present.

Is there anything else I should check on the GitHub side?

Also, this does apparently not only affect repositories from this one organization, but other repositories in my personal account and in another organization too:

- https://github.com/cfra/deadman-web/
- https://github.com/westnetz/prometheus-westnetz/

**Comment by rarkins** [comment]
I've forced a sync and the PicturePipe repos are now showing up as installed again so they should be scheduled within the next 2 hours.

The other repos are classified as stale and removed from regular scheduling as they have not received commits in too long. If you check the rebase/retry button on any PR then you should see it run and update, although it will still be classified as stale until you commit something to the main branch.

**Comment by cfra** [comment]
Okay, thank you for the prompt response.

Regarding the other repositories: Is there some more documentation about when a repository will be considered stale? I was not aware that Renovate will stop proposing updates if a repository has not seen changes for some time.

**Comment by rarkins** [comment]
No, we don't have it documented, and it's subject to change at any time. Essentially it's resource optimization - neither we nor GitHub gains anything by hammering their API hourly for a repo that hasn't been updated in a year. Currently the threshold is 60 days inactivity before it's put on a de-prioritized schedule.

**Comment by cfra** [comment]
Okay, thank you again for taking the time to explain. :bowing_woman:

**Comment by cfra** [comment]
Sorry, for reopening this issue, but we are still running into a problem:

**Comment by cfra** [comment]
Sorry, for reopening this, but I am still running into a problem:

https://app.renovatebot.com/dashboard#github/PicturePipe/ppa_traefik

For this repository, I can only see two runs in the dashboard.

The second run (yesterday) produced updates, but did not result in any PRs because the schedule did not match.

I updated the config so PRs would be opened immediately: https://github.com/PicturePipe/renovate-config/commit/0a09e449b9419f70eb01130ee74a88f273047dac

But renovate did not run again for the ppa_traefik repository, and no PRs have been opened.

I am at a loss why that is and what I should be doing differently. :confused:

**Comment by cfra** [comment]
Re-adding the repo solved this problem for now.
