### ISSUE TITLE
[Question] No webhook nor onboarding PR for my GitLab project

### ISSUE THREAD

**Issue by andyli** [renovatebot/app-support#11]
### Which Renovate are you using? CLI, App, or Pro
GitLab App, set up with the dashboard.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitLab.com

### Have you checked the logs? Don't forget to include them if relevant
Yes, there is my repo ([giffon.io/giffon](https://gitlab.com/giffon.io/giffon)) on the side bar, but there is no log.

### What is your question?
I don't see any webhook in the GitLab project setting page (settings -> integrations). There is no onboarding PR.

**Comment by rarkins** [comment]
Hi, your repo is now onboarding: https://gitlab.com/giffon.io/giffon/merge_requests/1

I will try to troubleshoot the lack of Webhook some other time. Do you see anything in the console log if you uninstall/install using the dashboard?

**Comment by andyli** [comment]
Here you are:
![renovatebot](https://user-images.githubusercontent.com/103977/66979070-c466fb00-f0de-11e9-8e2b-2add953d6387.png)
The last 2 lines appear after I uninstall and install. The ones before that was already there when I open the settings.
