### ISSUE TITLE
Renovate not running jobs on one of our repositories

### ISSUE THREAD

**Issue by carlobeltrame** [renovatebot/app-support#110]
Hi! We have successfully activated Renovate on a few repositories in the past few weeks, and it's working out great! However, in one of them (https://github.com/ecamp/hal-json-vuex) no jobs are being run. It looks to me like renovate is considering the repo as stale, since at the time of opening the onboarding PR, no commits were made for 2 weeks. However, since then (before merging the onboarding PR) we have had some non-renovate commits.

I was able to update the configuration and I can also trigger jobs using the master issue "trigger request" checkbox. But I'd like to have it automated, just like one of the other repos in the same organization.

**Comment by rarkins** [comment]
It seems to have been running now. It was actually in onboarding status, not stale. We run automatically against onboarding once per day and manually enqueue stale ones ~weekly

**Comment by carlobeltrame** [comment]
Indeed, thanks! Renovate is great!
