### ISSUE TITLE
The renovate bot stopped working on gitlab

### ISSUE THREAD

**Issue by CyrilQuandalle** [renovatebot/app-support#111]
Which Renovate are you using?
WhiteSource Renovate App

Which platform are you using?
GitLab.com

Have you checked the logs? Don't forget to include them if relevant
Well, there is some logs but I cant read them, it is loading forever.

What would you like to do?
The Renovate bot worked perfectly with my GitLab account and since the begining of the month it stopped doing anything and the logs are not readable anymore.

**Comment by rarkins** [comment]
Please see #103

**Comment by CyrilQuandalle** [comment]
> Please see #103
Thank you very much for your quick reply.
