### ISSUE TITLE
Repository is a fork and not manually configured (with includeForks: true)

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/app-support#114]
[This repo](https://github.com/krangence/hacksm/blob/master/.github/renovate.json5#L9) has `includeForks` set to true, however, the bot is throwing the following error in the logs & doesn't continue.

```
Repository is a fork and not manually configured - skipping
```

I can't see anywhere in the code this scenario would make sense other than if the renovate JSON was being misinterpreted.

**Comment by rarkins** [comment]
It seems we haven't documented this properly, because it's only supported when the file name is `renovate.json`

**Comment by ChipWolf** [comment]
Oh right, thanks! Can it still live in `.github` or does it have to go back to the root @rarkins?
Also, just out of curiosity, why does the filename matter? I thought `.json5` was just treated as an [alternate](https://github.com/renovatebot/renovate/issues/3484).

**Comment by rarkins** [comment]
Because when it's a fork we don't want to clone the whole repo just in case it has a config file. Instead we do a single API request to check if renovate.json returns a value and then checks if it includes the field. Therefore can't be in .github either.

The hosted app has been installed into 100,000 forks so the difference in load on GitHub is significantly less by avoiding a clone.

**Comment by ChipWolf** [comment]
Ouch, alright; that makes a lot more sense.
If I add a `renovate.json` into the root of the repo with the following, will it go and look for the other file?
```json
{ "includeForks": true }
```

**Comment by rarkins** [comment]
Unfortunately I think renovate.json takes preference

**Comment by rarkins** [comment]
We may be able to do some git tricks to fetch just a file list or limited clone but would need research done first

**Comment by ChipWolf** [comment]
Ah, so sparse checkouts/clone filters/etc.? That'd be way better than cloning the entire repo

**Comment by jakesylvestre** [comment]
I'd also be in favor of a proposal to support this behavior. In the meantime, it'd probably make sense to update [this](https://docs.renovatebot.com/configuration-options/#includeforks) portion of the docs to reflect this behavior.

I tried looking for a docs repo but couldn't find one. If you can point me in that direction, happy to submit a PR

**Comment by rarkins** [comment]
Check out the docs/ folder in this repo for sources

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
