### ISSUE TITLE
Forking Renovate not running on new repositories

### ISSUE THREAD

**Issue by chingor13** [renovatebot/app-support#115]
We have [Forking Renovate](https://github.com/apps/forking-renovate) installed org-wide, however, some new repositories seem to be ignored by the bot.

Examples:
* https://github.com/googleapis/java-artifact-registry
* https://github.com/googleapis/java-domains

Note: these repositories were created as private repositories and then made public. New repositories that were created as public seem to be found.

Is there a way to trigger a rescan across our org or trigger a repository to be watched?

**Comment by rarkins** [comment]
Those repos were flagged as disabled (Renovate-wise) at one point, so removed from the usual rotation. We periodically recheck the full disabled list but I've manually reset the disabled status of all repos in your org so that they should be rechecked again within the next few hours maximum

**Comment by rarkins** [comment]
Those two repos in particular have already run now. We'll look to add the ability to manually force a run through the dashboard one day..
