### ISSUE TITLE
Renovate Bot running out of disk space

### ISSUE THREAD

**Issue by Robula** [renovatebot/app-support#116]
Our monorepo is causing the Renovate container to run out of space with errors. The Renovate Dashboard is failing with `unknown error`, see job #318704723. The errors in the log contain line such as:
`ENOSPC: no space left on device` & `Error: error: unable to write file`

A local repo with after Yarn install:
```sh
❯ du -sh .
4.2G    .
```

Other than putting our repo on a diet, is there anything we can do in the interim?

Many thanks

**Comment by rarkins** [comment]
What's the repo name or a recent job ID? I can try switching it to an alternative storage which has ~10GB available

**Comment by Robula** [comment]
Hi @rarkins, thanks for your reply. The most recent job ID is 318927124.

**Comment by oleg-preply** [comment]
facing the same issue (`du -sh . 3,9G    .`)

@rarkins, does it makes sense to try switching my project to alternative storage as well? (job ID is 323611975). Or there is another workaround (apart from removing packages from the project :joy:)?

Anyway, thank you for your efforts!

**Comment by MarcPorciuncula** [comment]
Hi, been having the same issue. Recent Job ID is `#325821918`.

```
> du -sh
4.9G    .
```

Thanks!

**Comment by davazp** [comment]
And another case having the same issue here 🙏 .  Right after install is `3.6G`.  It fails later on with
`ERROR: Disk space error - skipping`.  I still get some updates from the beginning of the job though, for now.

A recent jobs id is `#335030007`.

**Comment by trovato-tech** [comment]
Hey @rarkins, unfortunately we're also experiencing this issue. Recent job id is `#341826578 `

Thanks a lot!

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
