### ISSUE TITLE
Gitlab webhooks not installed

### ISSUE THREAD

**Issue by bartlangelaan** [renovatebot/app-support#14]
This is a kind of follow up on issue renovatebot/renovate#2807.

**What Renovate type are you using?**
Renovate App for Gitlab

**Describe the bug**
When I enable a repository trough te Renovate Dashboard, the Renovate user is correctly added to the repository. The only thing is: the webhook is not installed. Even after waiting for the project to show up on the left side, and opening the project list, it fails to add the webhook.

**Screenshots**
This part works perfectly:

![image](https://user-images.githubusercontent.com/1851670/57127746-9e98a480-6d91-11e9-8088-db482d6de3c0.png)
![image](https://user-images.githubusercontent.com/1851670/57127775-ace6c080-6d91-11e9-92fb-8ee171965118.png)
![image](https://user-images.githubusercontent.com/1851670/57127787-bc660980-6d91-11e9-982e-08e3cb804c1d.png)
👆 This returns an empty array

Then it tries to make a call to the Renovate API to add the webhooks:
![image](https://user-images.githubusercontent.com/1851670/57127877-051dc280-6d92-11e9-92d3-127f9a1d4649.png)
![image](https://user-images.githubusercontent.com/1851670/57127890-09e27680-6d92-11e9-842b-f2036f08e5aa.png)

It's a project that is in a subgroup by the way, in case that matters.

If there's anything I can do to help debugging, please let me know.

**Comment by esetnik** [comment]
I still am having this. @rarkins is it on your radar?

**Comment by monochromata** [comment]
Works for me too, yay :-)
