### ISSUE TITLE
[Question] Is there an issue with the bot schedule?

### ISSUE THREAD

**Issue by julienmonnard** [renovatebot/app-support#17]
Hello! I hope I'm in the right place for that.

We have the Renovate bot installed and running nicely for about a month on our Github private repository (DND-IT/cms-frontend) with the Github App, but it seems that it is not being scanned anymore, the bot doesn't react to anything.

What I tried:
- click the "rebase" checkbox in a couple of created PR's
- merge an existing Renovate PR
- one slot is free to create a new one (related to "prConcurrentLimit")
- created an "Update Renovate config" PR

What's left to try:
- Asking you :-)
- Uninstall/re-install the Github App

Usually, the bot is triggered after a delay from a few seconds to max 5 minutes, but now it has been hours since it did anything. The last known run was done on the 8th of December at 5.26am (CET).

I also don't know where to find logs if there is any accessible.

Thanks in advance for your help :-)

**Comment by rarkins** [comment]
Can you retry the rebase checkbox again now?

**Comment by julienmonnard** [comment]
Yes, it seems that everything is coming back up, thank you!
Was is something we did wrong?

**Comment by rarkins** [comment]
No, there was a problem on the server side, sorry. The bot had problems signing commits so was exiting. FYI you can see logs at renovatebot.com/dashboard in future

**Comment by julienmonnard** [comment]
Ok, good to know! Thank you again
