### ISSUE TITLE
PRs not being created

### ISSUE THREAD

**Issue by nick** [renovatebot/app-support#2]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
I merged the renovate config into master, but am not seeing the PRs with the changes

**Did you see anything helpful in debug logs?**
https://renovatebot.com/dashboard#github/OriginProtocol/origin could be related? It says 'registry-failure'

**Comment by rarkins** [comment]
This should now be resolved. Onboarding repos are only queued daily, while enabled repos are queued hourly. Upon detecting a merged onboarding PR, we queue a job which normally serves to update the status from onboarding to enabled. In this case we got unlucky with npmjs erroring during that job and as a result the repo remained classifed as onboarding and hence scheduled only daily.
