### ISSUE TITLE
Renovate dashboard not showing any repos in sidebar

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/app-support#20]
I'm slowly moving away from self-hosting renovate to using Renovate's GitLab App now that it is free (thanks again).

So I've added `@renovate-bot` to some repos on GitLab and registered on the dashboard. However, I can't see any repos in the sidebar of the dashboard, they simply do not populate?

**Comment by rarkins** [comment]
Actually now is unfortunately a bad time to migrate! Something has triggered a rate limiting today that’s blocking Renovate from processing most repos. If there are no successful jobs then you won’t see any entries in the sidebar yet

**Comment by Jamesking56** [comment]
Ah right OK, happy to wait for rate limiting issues to be resolved thanks for letting me know :+1:

Is there or will there be a status page for hosted renovate?

**Comment by rarkins** [comment]
One day. For now I just tweeted a notification after receiving confirmation from GitLab that it’s a new rate limiting that triggered it.

**Comment by Jamesking56** [comment]
Cheers @rarkins
