### ISSUE TITLE
Not receiving pull requests on a GitHub repo

### ISSUE THREAD

**Issue by emmatown** [renovatebot/app-support#22]
Hey there 👋

I've added the Renovate app to https://github.com/keystonejs/keystone a little bit ago and it hasn't received any pull requests. I've tried adding a config and reinstalling the app but that didn't change anything. It's showing up in the dashboard but there aren't any jobs/logs for the repo.

Thanks in advance for your help 😃

**Comment by rarkins** [comment]
Can you do the following?
- go to https://github.com/apps/renovate
- Click the "Configure" button
- Select "keystonejs" from the list of options
- Enter password if prompted
- Scroll to the bottom
- Take a screenshot of what you see

It should show a list like this:

![image](https://user-images.githubusercontent.com/6311784/71884874-0e390d80-3131-11ea-86af-a9e76599525f.png)

(screenshot taken from my view of of the `renovatebot` org)

**Comment by emmatown** [comment]
<img width="588" src="https://user-images.githubusercontent.com/11481355/71887358-a19e2d00-3189-11ea-8b94-1bd2da2fbcc8.png">

**Comment by rarkins** [comment]
Thanks for that confirmation. GitHub's API does not appear to be returning that repository in the list of installed accounts, so I will debug it a little to be sure and then raise a support ticket with GitHub if necessary.

**Comment by rarkins** [comment]
Hi there, closing this as I believe it's all running properly now.

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
