### ISSUE TITLE
WhiteSource Renovate GitLab app commits are unverified

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/app-support#24]
**What Renovate type are you using?**

Renovate GitLab App

**Describe the bug**

Commits by the Renovate user are unsigned / unverified.

**Did you see anything helpful in debug logs?**

_Irrelevant_

**To Reproduce**

1. Hook GitLab repository up to Renovate GitLab
2. Wait for a renovate PR
3. View the commit to see GitLab shows it as unverified:

![screenshot](https://user-images.githubusercontent.com/253237/72362586-52a54a00-36eb-11ea-9fe5-e3b2fe910ed7.png)

**Additional context**

I think the bot user just needs a valid GPG key adding that matches what the app uses.

**Comment by Jamesking56** [comment]
This still looks to be an issue for me

**Comment by rarkins** [comment]
Yes, it’s still an open issue

**Comment by rarkins** [comment]
I've attempted to copy over the GPG key to the right account on GitLab.com right now, but I'm seeing neither verified or unverified feedback on existing commits I checked:
![image](https://user-images.githubusercontent.com/6311784/76977633-dbcc3d80-6935-11ea-8291-14fa4787fba2.png)

**Comment by rarkins** [comment]
OK here we go:
![image](https://user-images.githubusercontent.com/6311784/76978128-9bb98a80-6936-11ea-971b-a5694054b6e4.png)

Seems like you might need to be in Branch view to see it. In MR view I don't see any indication:

![image](https://user-images.githubusercontent.com/6311784/76978203-b429a500-6936-11ea-9a8a-e02ca0b311aa.png)

**Comment by Jamesking56** [comment]
Thanks @rarkins :+1:
