### ISSUE TITLE
Poetry lock file does not get updated 

### ISSUE THREAD

**Issue by cfra** [renovatebot/app-support#26]
**What Renovate type are you using?**

We are using the GitHub app.

**Describe the bug**

We are using Poetry to manage our Python dependencies. This worked fine for a long time. :slightly_smiling_face: 

Recently, the pull requests opened by Renovate fail to update our `poetry.lock` file, which worked fine in the past.

**Did you see anything helpful in debug logs?**

```text
INFO: Branch needs creating(branch="renovate/watchdog-0.x")
DEBUG: Using parentBranch: undefined(branch="renovate/watchdog-0.x")
DEBUG: manager.getUpdatedPackageFiles()(branch="renovate/watchdog-0.x")
DEBUG: Replacing `0.9.0` with "0.10.0" at index 1321(branch="renovate/watchdog-0.x")
DEBUG: Updating packageFile content(branch="renovate/watchdog-0.x")
DEBUG: poetry.updateArtifacts(pyproject.toml)(branch="renovate/watchdog-0.x")
DEBUG: No lock file found(branch="renovate/watchdog-0.x")
```

**To Reproduce**

The problem can be seen here: https://github.com/cfra/poetry-problem/pull/2

poetry.lock should be updated, but it isn't.

**Comment by rarkins** [comment]
I think I've found and fixed the problem in the app - a relative local path was set incorrectly for poetry. Example fixed PR here: https://github.com/rarkins/renovate-repro/pull/1/files

Can you rebase your 3.7 PRs and verify it's fixed for you too?

**Comment by itajaja** [comment]
oops somehow I didn't read this yestarday. I tried, and worked. thanks! much appreciated 🙏

**Comment by rarkins** [comment]
Thanks for your help debugging it and sorry for the inconvenience it caused!
