### ISSUE TITLE
npm registry-failure due to ECONNRESET / parse error

### ISSUE THREAD

**Issue by henrist** [renovatebot/app-support#28]
**What Renovate type are you using?**

Hosted App

**Describe the bug**

An excessive amount of job runs fails with registry-failure. For the job log available, only two runs did not fail.

**Did you see anything helpful in debug logs?**

See e.g. job ID 140436240 (and the image below for more jobs)

I've checked multiple jobs, and they all seem to fail on `https://registry.npmjs.org/@typescript-eslint%2Feslint-plugin`.

I have lots of other projects set up in Renovate Bot for other organizations and I have not seem the same error there for those I checked.

**To Reproduce**

Not sure how I can easily reproduce this outside the repo, as this is a monorepo with 3 `package.json` files + locks, some Python setup.py + requirements.txt files and quite some pom.xml files. I don't know if this is the reason for the failure, but I'd guess it might be related.

**Additional context**

![image](https://user-images.githubusercontent.com/703354/74250543-0dc10300-4ceb-11ea-8b89-e50583be0134.png)

**Comment by rarkins** [comment]
Thanks for raising the issue. I noticed recently that we're seeing frequent errors for some `@graphql-codegen/*` and `@typescript-eslint/*` packages. Do you use the same package in other repositories and *it works*?

**Comment by henrist** [comment]
Yes, I have other projects using the same package that is reported to fail under this project. Example: https://github.com/capraconsulting/webapp-baseline

I see no errors for the last job runs for that project. I haven't yet come across any of my projects having the same issue, but I haven't checked all 100+ of them.

The last failure, job ID 140444181, has an interesting failure. It fails on this:

```
"err": {
    "name": "ParseError",
    "host": "registry.npmjs.org",
    "hostname": "registry.npmjs.org",
    "method": "GET",
    "path": "/@typescript-eslint%2Feslint-plugin",
    "protocol": "https:",
    "url": "https://registry.npmjs.org/@typescript-eslint%2Feslint-plugin",
...

    "statusCode": 200,
    "statusMessage": "OK",
...
    "message": "Unexpected end of JSON input in \"https://**redacted**@typescript-eslint%2Feslint-plugin\": \n{\"_id\":\"@typescript-eslint/eslint-plugin\",\"_rev\":\"568-167d321491e42adfc9d4a8f...",
    "stack": "ParseError: Unexpected end of JSON input in \"https://**redacted**@typescript-eslint%2Feslint-plugin\": \n{\"_id\":\"@typescript-eslint/eslint-plugin\",\"_rev\":\"568-167d321491e42adfc9d4a8f...\n    at EventEmitter.emitter.on (/home/ubuntu/renovateapp/node_modules/got/source/as-promise.js:65:26)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
...
```

And the body logged is, well, long. The file on NPM is 14 182 932 bytes long. A big extreme if you ask me just to know if there are new versions available. Must be a huge amount of bandwidth wasted on all this transfer for all packages every job run :)

Also note that the body from the HTTP call in the debug message is actually formatted. I find that a bit odd.

![image](https://user-images.githubusercontent.com/703354/74258703-0bfd3c80-4cf7-11ea-906e-dff54f46f61d.png)

**Comment by rarkins** [comment]
That's really surprising that your other project has not been having the same problem. Unless it's a wild coincidence/bad luck for the first repo you described, this surely must point to something, but it eludes me so far.

I checked the logs and found some ECONNRESET errors for packages with only ~200kb downloads too.

BTW the Renovate app parses then caches results from npmjs (shared across all workers) so it's not as much downloading as you might expect.

**Comment by eostman** [comment]
We are seeing the same issue for job id 140660288 and in another of our repositories for id 140553848.

**Comment by henrist** [comment]
@rarkins I checked the last 20 job runs and they all failed with either ECONNRESET for https://registry.npmjs.org/@typescript-eslint%2Feslint-plugin or the parse error I showed above. Whas the ECONNRESET you saw for other packages only for other repos?

@eostman Do you have consistent errors for a given package like the image I posted or only sporadic errors?

**Comment by rarkins** [comment]
> Whas the ECONNRESET you saw for other packages only for other repos?

Sorry, what do you mean exactly? I'm seeing 40-50 connection resets per hour, of which around half of those are typescript-eslint or graphql-codegen. It's a really big surprise to me if lookups for the same packages work all the time for certain repositories while failing nearly all the time for others.

**Comment by henrist** [comment]
> Sorry, what do you mean exactly? I'm seeing 40-50 connection resets per hour, of which around half of those are typescript-eslint or graphql-codegen. It's a really big surprise to me if lookups for the same packages work all the time for certain repositories while failing nearly all the time for others.

Thinking of this:

> I checked the logs and found some ECONNRESET errors for packages with only ~200kb downloads too.

I was wondering if you saw this (concistently) on _other repos_, so that the bot "never" runs successfully. I'd expect you get some random ECONNRESET naturally due to unstable network etc, but nearly every run like in my case is strange.

**Comment by rarkins** [comment]
Right now I only have the ability to check anecdotally/manually, but I didn't observe another case of another URL failing every single time. The ones with smaller packages that I checked might have 2-3 failures per day though, so enough for me to consider it regular/consistent.

**Comment by henrist** [comment]
Jumping from version 19.131.2 to 19.131.4 the jobs seems to be running successfully again.

![image](https://user-images.githubusercontent.com/703354/74328079-91333080-4d8d-11ea-81e5-6c4f2261e2cb.png)

I see you added some changes just now (https://github.com/renovatebot/renovate/commit/13a673665986ce9bb4c82870dab48f178cdcaead) that got part of 19.131.5, so I guess that it working again is not due to this change.

**Comment by rarkins** [comment]
> Jumping from version 19.131.2 to 19.131.4 the jobs seems to be running successfully again.

I don't think there were any fixes in that version that would affect things, however I *did* also update our running version of Node 12 behind the scenes. I would be celebrating the news except that I don't detect any noticeable drop in the total stats.

**Comment by eostman** [comment]
> @rarkins I checked the last 20 job runs and they all failed with either ECONNRESET for https://registry.npmjs.org/@typescript-eslint%2Feslint-plugin or the parse error I showed above. Whas the ECONNRESET you saw for other packages only for other repos?
> 
> @eostman Do you have consistent errors for a given package like the image I posted or only sporadic errors?

In one of our repositories the issue has happend sporadicly, in the other one  it looks like the image below
![image](https://user-images.githubusercontent.com/1128095/74339820-7cff2b80-4dad-11ea-8e5a-a4e291606588.png)

**Comment by rarkins** [comment]
Do you both have npm tokens configured in these repos' configs, e.g. for your own private packages?

**Comment by eostman** [comment]
We do yes

**Comment by rarkins** [comment]
Good news - I think the retry mechanisms I added today may have finally worked. I see logs of recovering from ECONNRESET errors in equal quantity to logs of retrying them.

**Comment by henrist** [comment]
That's great! I have not seen any more errors since before the changes.

> Do you both have npm tokens configured in these repos' configs, e.g. for your own private packages?

No NPM tokens configured on this part.

**Comment by UberMouse** [comment]
Just chiming in here to say this is also affecting me. It's gotten better since yesterday, gone from a close to 90%+ failure rate to somewhat less, still high. No NPM token is configured for private packages. All the errors do happen on @typescript-eslint or @graphql-codegen packages. I've seen it fail for a variety of the packages under those scopes.

Out of the previous 148 runs I can see in the dashboard 128 have had a registry-failure. This is in the past 3 days.

**Comment by rarkins** [comment]
@UberMouse what repository / job ID?

**Comment by UberMouse** [comment]
@rarkins Job ID #141306747

**Comment by rarkins** [comment]
OK. It seems we have progressed past `ECONNRESET` errors (by retrying extra) but now still get frequent `JSON.parse()` errors due to incomplete data returned. I guess we can keep tracking in this issue.

**Comment by rarkins** [comment]
We are now retrying `ParseError` results from npmjs too, which should lead to a higher completion rate. Global stats are improving and anecdotally it appears to be working on repositories I've checked. Anonymous example:

![image](https://user-images.githubusercontent.com/6311784/74521700-219e7c00-4f1a-11ea-89d2-f9fab1a37e02.png)

Too soon to celebrate though considering every time we whack a mole a new one raises its head.

**Comment by UberMouse** [comment]
Thanks @rarkins! Perfect now, haven't had a failure since then.

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
