### ISSUE TITLE
Renovate GitLab App ignoring my repo

### ISSUE THREAD

**Issue by Jamesking56** [renovatebot/app-support#29]
I just noticed that a while back I hooked up a repo to Renovate and no renovations are happening at all. There is a valid `renovate.json` file and it has an Onboarding MR that has merged.

https://app.renovatebot.com/dashboard#gitlab/momentumstudio/composer-repository

**Comment by rarkins** [comment]
Repos with no commits for 2+ weeks get marked as "stale" and retried only ~weekly or if meaningful commits happen before then (renovate.json, package.json, etc). According to our DB, the last two checks:

![image](https://user-images.githubusercontent.com/6311784/74913658-62d2d800-53c1-11ea-839b-a5f0427dc2dc.png)

**Comment by Jamesking56** [comment]
OK, the dashboard doesn't show me any renovations at all, just a blank list which is what confused me a bit.

I think it would be good if the dashboard said that the repo was stale

**Comment by rarkins** [comment]
Yeah, the dashboard shows only the last 3 days of logs. Showing the repository status is a good idea

**Comment by Jamesking56** [comment]
I have another repo this is happening to, but this one **has** been updated today (and has a new tag as well).

This one is a public repo, so might be easier for you to troubleshoot with.

https://app.renovatebot.com/dashboard#gitlab/momentumstudio/laravel-theme
https://gitlab.com/momentumstudio/laravel-theme

**Comment by Jamesking56** [comment]
This is still happening for me here as well https://app.renovatebot.com/dashboard#gitlab/momentumstudio/magento2shopify
