### ISSUE TITLE
"Artifacts update problem" with private packages / custom registry (encrypted .npmrc)

### ISSUE THREAD

**Issue by fabianbru** [renovatebot/app-support#31]
**What Renovate type are you using?**
Renovate GitHub App

**Describe the bug**
Private packages or packages from custom registries are not found in the "artifacts" step. So the renovate PR will have the ":warning: Artifact update problem" warning and the failing check "renovate/artifacts".

I have submitted a bug some time ago for issues with those packages (private or custom registry) in the "find new version" step, see renovatebot/renovate#3417. Perhaps this is related?

For what it looks like is that in the "artifacts" step the (encrypted) ".npmrc" content is not used, so no NPM_TOKEN or custom registry?

Notes:
- I am using an encrypted ".npmrc" string in the "package.json".
- I am using yarn
- I have a yarn monorepo
- The issues appears on both packages (private on npm registry AND private on custom registry)

**Did you see anything helpful in debug logs?**
The Dashboard doesn't work at the moment (will update if its working again), but last I looked into there was nothing helpful. Just the warning that is also in the PR comment:
```
package "@xyz/privatePackage@X.Y.Z" required by "@my/monorepoPackage@X.Y.Z" on the "npm" registry.
```

**To Reproduce**
See issue renovatebot/renovate#3417. Same setup and same encrypted ".npmrc". After that issue was resolved renovate found new versions, but on my scheduled time the issue above happened.

**Expected behavior**
Artifacts should be build correctly ("yarn.lock") for private packages with NPM_TOKEN or packages from custom registries.

**Comment by viceice** [comment]
I've seen such auth problems too on our self-hosted renovate cli (docker-slim). 

We have a `.npmrc` and `.yarnrc` file in our repo root. I've tried to configure the `npmrc` renovate config option to add auth, which doesn't work. My workaround is to add a `.npmrc` with the auth to `/home/ubuntu/`

As i tried the last time we need to use username and password auth (against proget npm registry), maybe that was a problem too. now we use verdaccio.

**Comment by Geit** [comment]
Thanks for the prompt reply @rarkins - I've created a small reproduction repo and attached it to the Renovate hosted application. The job ID for its first run was #147251406 and I've also added you as a collaborator to the repo on the off chance that helps.

**Comment by albanv** [comment]
Hi guys,
we encounter the exact same issue using a private registry hosted by us (verdaccio) with the public renovate app:
- the code is hosted in a private github repository and **does not** contain a `.npmrc`/`.yarnrc` file and is not a monorepo
- the renovate-config is also hosted in a private github repo, and contains an encrypted npmToken
- then on each renovate PR we encounter the `Artifact update problem` related to `yarn.lock` update

**Comment by mbrandau** [comment]
> * then on each renovate PR we encounter the `Artifact update problem` related to `yarn.lock` update

I'm experiencing the same issue with verdaccio and a self hosted GitLab instance.

**Comment by Sy1v4in** [comment]
Hi guys,
we encounter the exact same issue using a private registry hosted on **`Github packages`** with the public renovate app:

  - the code with the renovate-config is hosted in a private github repository and does not contain a .npmrc/.yarnrc file and is a single simple application repository,
  - the `.npmrc` is configured through an encrypted `npmrc` string in the `renovate.json` file,
  - then on each renovate PR the right version is computed but we encounter the `Artifact update problem` related to `yarn.lock` update

Any update on this problem?

Thanks 🙏

**Comment by viceice** [comment]
We recommend to use hostrules only instead of npmrc. That way we got most auth issues resolved.

Please open a discussion with detailed reproduction steps. Or search discussions / docs. There are plenty of samples for different registries.

**Comment by viceice** [comment]
We are also planning to remove npmrc config option at all. So renovate would only read repo npmrc for registry urls.

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
