### ISSUE TITLE
Reconfiguration PR not being validated, logs not showing

### ISSUE THREAD

**Issue by leaumar** [renovatebot/app-support#32]
I'm using the gitlab bot on some active repos with success. I filed reconfiguration PRs on 2 of them several hours ago and see no interaction with them by the bot yet. 

- https://gitlab.com/Marnes/image-background-color-picker/-/merge_requests/14
- https://gitlab.com/Marnes/doubleclick-image-downloader/-/merge_requests/34

In the meantime the bot has been running (several log entries visible) and even been filing dep update PRs and detecting code changes that I added to them, so I'm a bit confused by it doing one thing but not another. Do renovate's different jobs actually run at different schedules?

Sorry if this is just a matter of waiting longer, but the docs, existing issues, and my limited insight/experience with the bot (like instant reaction to dep update PR changes) paint a certain expectation, and I read that onboarding and reconfiguring are the scheduler's top priorities, so when it doesn't come true then I feel there must be something wrong or knowledge missing...

On a related note, the logs for 1 of my repos never load:
![image](https://user-images.githubusercontent.com/3950300/75709208-84399b00-5cc2-11ea-94ff-f63a861f6b24.png)

--

All that aside, I wanna say thanks for making this awesome tool and making it free :) It works like a charm (these hiccups/misunderstandings aside), definitely relieves me of some work, and makes very convenient use of gitlab's/github's facilities 👍

**Comment by leaumar** [comment]
After 3 days there has been no change, so I think something must be broken or the docs are simply not correct anymore. In the meantime I've received a welcome email from someone from whitesource. Can I take this issue to that person, or is this repo still the place to go for tech support?

**Comment by rarkins** [comment]
Sorry for the delay in getting back to you. I'm not sure that reconfiguration feedback is supported on GitLab for now but will look into it to confirm. It's not like the full Onboarding PR with descriptions - it just validates the config and then adds a pass or fail checkmark. You can add this functionality to your pipelines or run it manually itself using the [config validator](https://github.com/renovatebot/renovate/blob/master/bin/config-validator.js) that ships with `renovate` using the name [`renovate-config-validator`](https://github.com/renovatebot/renovate/blob/1b05a3bf7b578c4f09de74256aae3b4c35c904bf/package.json#L7)

For the one that doesn't load, can you check the console and network activity log to see if there's any hint as to what's failing?

**Comment by leaumar** [comment]
Oh ok, that makes sense. Thanks for the tip.

![image](https://user-images.githubusercontent.com/3950300/76024880-25775a00-5f2c-11ea-99f7-bcf5681d4593.png)
First 4 calls were for loading a working project. Bottom 2 for the one that's stuck. `https://v1.renovateapi.com/gitlab/repos/Marnes/image-background-color-picker/jobs` returns `403`. These are solo projects under my ownership and my repo configurations are all vanilla, so I'm not sure why this app would be getting that error.

**Comment by rarkins** [comment]
I might know why. GitLab have an API bug where it returns an empty permissions level in some cases, and the Renovate API validates that you have write access to a repo in order to view the logs. No permissions level means you get denied access. There's a workaround by including a minimum permissions level in the url query string itself, and then performing no client-side validation. I'll see if I can find the code.

Curiously though, does that repo show up in the sidebar of all repos after you log in?

**Comment by leaumar** [comment]
Yeah, it shows up the same as the rest:
![image](https://user-images.githubusercontent.com/3950300/76025958-34f7a280-5f2e-11ea-9f4e-315a71b6dd6e.png)
![image](https://user-images.githubusercontent.com/3950300/76025978-3e810a80-5f2e-11ea-92a1-05d9e0404486.png)

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
