### ISSUE TITLE
a community to report bugs

### ISSUE THREAD

**Issue by piotr-s-brainhub** [renovatebot/app-support#34]
As `renovate` community is already big and it's still growing, I thought it would be great to have a place to report breaking changes occurring in a new patch or minor version e.g. https://github.com/Automattic/mongoose/issues/7660

I see the following categories:
- serious vulnerability - a new version is a real virus e.g. sending somewhere the content of local files - IMO, even NPM should get rid of something like that
- potential vulnerability - a new version allows SQL injection or something like that
- critical bug - either everything is broken or some of the most essential features don't work at all
- major bug - it doesn't work only for some specific params/ options but which occur relatively often
- minor bug - it doesn't work only in some extremely rare situations
- potential bug - some people can consider it as a bug while others not

A given version is labeled only if it introduces a bug or a vulnerability that wasn't existent for the previous version.

Thanks to such a system, I could configure Renovate to skip breaking dependencies or update them in separate PRs.

**Comment by rarkins** [comment]
We are definitely looking to harness crowd feedback on PRs for the benefit of users. I've moved this to app support because it would be something that utilizes the app's data rather than baked into the OSS code itself.

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
