### ISSUE TITLE
Only the first 100 projects are found when adding projects with gitlab

### ISSUE THREAD

**Issue by mjrider** [renovatebot/app-support#35]
**What Renovate type are you using?**
Gitlab

**Describe the bug**
Whwn adding projects with gitlab, only the first 20 are found ( pagination in the api ? )

**Did you see anything helpful in debug logs?**
n/a/

**To Reproduce**
1. open dashboard with gitlab login with an account with access to more then 20 projects
2. click on ⚙️
3. count the projects, and compare them with the actual list

**Expected behavior**
see more then 20 projects

**Screenshots**
![image](https://user-images.githubusercontent.com/213105/50838529-80c8af00-135e-11e9-8c2a-335f03bc527c.png)

**Additional context**

**Comment by mjrider** [comment]
i don't see anything different atm, is it already live ?

**Comment by Raimmaster** [comment]
Any news regarding this issue? Given that [#65](https://github.com/renovatebot/app-support/issues/65) also had this. Or perhaps any current workaround to get the projects we're looking for to use Renovate?

**Comment by alecgerona** [comment]
@Raimmaster as mentioned by @rarkins in #60, you can just add Renovate bot as a developer/collaborator for your project and it will still work. The only caveat is its execution time which happens hourly rather than relying on a hook.

**Comment by Raimmaster** [comment]
I've added @renovate-bot to the repo, 21 hrs ago, but no integration MR has been received so far. Any reasons why this may be happening? Note: it does have Developer access.

**Comment by alecgerona** [comment]
I believe I waited a bit more for mine. YMMV. If it still doesn't appear then something may be wrong.

**Comment by rarkins** [comment]
@Raimmaster what's the GitLab group or username this is under? I'll check if I can find any newly discovered repos in our DB

**Comment by Raimmaster** [comment]
The organization/group it's under is `leadiq`, @rarkins.

**Comment by rarkins** [comment]
@Raimmaster only one repo is detected (the web app). It syncs hourly, and is not seeing any others. Developer level should be enough for it to be detected though.

**Comment by Raimmaster** [comment]
Yes, that's the repo where it was added, but no MRs have been received so far.

**Comment by rarkins** [comment]
A job was in the queue, should be through now

**Comment by Raimmaster** [comment]
So it's been over 48 hours now, but there's no integration MR. Is the job still in the queue, @rarkins?

**Comment by rarkins** [comment]
@Raimmaster if you log into the dashboard, can you view the logs? There is an error that I think is caused by your branch naming restrictions

**Comment by Raimmaster** [comment]
If I log into the dashboard there's nothing there, this is a screenshot of it, even after I checked the repos cog to look for the project (which again, doesn't load because it loads exactly 100 projects and not the one I added @renovate-bot to).

![Dashboard](https://i.imgur.com/aRRjFR5.png)

**Comment by Raimmaster** [comment]
Is it possible you can share the error without disclosing any private details or anything else regarding this, @rarkins?

**Comment by rarkins** [comment]
If I had to guess, I think your branch naming restrictions don't allow the "renovate/*" prefix. 

Please don't continue following up in this issue though as it's not related to the original topic. Open a new issue if you need.

**Comment by rarkins** [comment]
Pagination should now be working for GitLab when you select the install option. Please comment here once you can test it to confirm it's fixed or reopen the issue
