### ISSUE TITLE
Automatically approve GitLab MRs when automerge is enabled

### ISSUE THREAD

**Issue by eddarmitage** [renovatebot/app-support#43]
I've been trying to get automerge configured for [one of my GitLab repositories](https://gitlab.com/eddarmitage/photo-import) using the hosted GitLab bot, but I believe the current stumbling block is that Renovate won't approve the MR, which is a requirement for the repo ([Sample MR](https://gitlab.com/eddarmitage/photo-import/-/merge_requests/134)).

The MR is marked as "🚦 Automerge: Enabled". The `@renovate-bot` user is configured as a CODEOWNER for the relevant files, and is correctly shown as a possible approver. I've seen that by me manually approving an MR, Renovate will merge it ([Example MR](https://gitlab.com/eddarmitage/photo-import/-/merge_requests/119)).

<img width="750" alt="Screenshot 2020-04-21 at 11 08 04" src="https://user-images.githubusercontent.com/700052/79854069-cc229780-83c0-11ea-9653-df37d5a03413.png">

I've seen the [Approval Bot](https://github.com/renovatebot/renovate-approve-bot) for GitHub, but my understanding is that that exists because GitHub does not allow the PR author to approve the PR (hence needing a second bot) - this isn't a rule on GitLab.

Does the GitLab Renovate bot have the ability to approve MRs, or else is there an equivalent of the GitHub approval bot that I'm not aware of/haven't understood how to set up? Ideally, I'd like for MRs to only be marked as approved when they have automerge enabled (in my case to prevent MAJOR updates being approved)

**Comment by kevincox** [comment]
This would be a fantastic feature. This way I could give renovatebot access just to the lock files (which I allow auto-merge for) without giving it permission to make other changes to the repo without approval.

**Comment by rarkins** [comment]
> I've seen the [Approval Bot](https://github.com/renovatebot/renovate-approve-bot) for GitHub, but my understanding is that that exists because GitHub does not allow the PR author to approve the PR (hence needing a second bot) - this isn't a rule on GitLab.

Your understanding is correct re: GitHub

> Does the GitLab Renovate bot have the ability to approve MRs

Please follow this feature request: https://github.com/renovatebot/renovate/issues/6577
