### ISSUE TITLE
App is refusing to rebase/retry a PR

### ISSUE THREAD

**Issue by ChipWolf** [renovatebot/app-support#47]
I'm having an issue with a couple of PRs on a repo [here](https://github.com/HRZNStudio/playhrzn-k8s/pull/20) and [here](https://github.com/HRZNStudio/playhrzn-k8s/pull/21).

After some heavy rebasing/reordering and squashing of commits on the master branch, I click the retry checkbox in the body of the PR, but nothing seems to happen.

Any help would be hugely appreciated on this. Thanks!

**Comment by rarkins** [comment]
If you log into the dashboard, are you seeing *jobs* being run? FYI I noticed some warnings in the logs earlier, I think they were for that repo. Missing `registryUrls` for a helm chart IIRC

**Comment by ChipWolf** [comment]
~~Aye yeah, that's probably because I haven't added the registry for the Pomerium deployment yet.~~ Done.

Jobs look like they're running, last one was 24 mins ago.

**Comment by rarkins** [comment]
If you filter by the branch name, you should see all the logs relating to it and hopefully get some idea of why the rebase didn't take effect. FYI if Renovate thinks there's no *changes* compared to what's on github.com then it skips doing a force push.

**Comment by ChipWolf** [comment]
This appears to have eventually resolved itself
