### ISSUE TITLE
Renovate bot doesn't raise MRs after onboarding renovate.json to new repo

### ISSUE THREAD

**Issue by y0zg** [renovatebot/app-support#53]
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?
GitLab.com

### What would you like to do?
I added `renovate.json ` into new repo but don't see any new MR after couple of days.
Note: current setup works for other repos already , but in current repo we don't use MR requests, just commits into `develop` branch. 

Is there anything I missed?

Thank you in advance

**Comment by rarkins** [comment]
What is the repo name? I'm pretty sure we have some rules in place to skip GitLab repos which have MRs disabled.

**Comment by y0zg** [comment]
Ehm, repo name `redhat-api`. Should I raise dummy MR to trigger the bot? Anything I can add into config in order to override this behavior?

`renovate.json`:
```
{
  "extends": [
      "config:base",
      ":pinSkipCi"
  ],
  "semanticCommits": false,
  "commitMessagePrefix": "Upgrade:"
}
```

**Comment by rarkins** [comment]
Do you mean that your repo has MRs enabled, but you disabled them for Renovate?

**Comment by y0zg** [comment]
Well, we don't have any restrictions on this repo (meaning this is similar repo as all other where renovate bot works) and user `@renovate-bot` has got Developer permission similar to other repos.
I have only an idea to create dummy MR as we currently merging directly into `develop` branch

**Comment by rarkins** [comment]
We don't have any detected repositories ending in `/redhat-api`. I will check if our scanning is working fine later.

**Comment by y0zg** [comment]
what about `/catalyst-api` repo name ?

**Comment by rarkins** [comment]
It ran 10 minutes ago and did not detect any repo with `redhat` in it. There are two repos ending in `/catalyst-api`.

**Comment by y0zg** [comment]
Let's try to solve this with `catalyst-api` Any idea what is wrong? Should I raise a dummy MR? The settings are the same as I described previously for `redhat-api` (not in scope currently)

Thank you in advance @rarkins for prompt replying! Much appreciate!

**Comment by rarkins** [comment]
Do you see logs for it when you sign in with your gitlab credentials to app.renovatebot.com ?

**Comment by y0zg** [comment]
Just dots or blank screen, I tried to re-install it by pressing "gear" icon about 1 hour ago but still the same. Any glue?

**Comment by rarkins** [comment]
Check developer tools if there’s any problem loading the page

**Comment by y0zg** [comment]
If I disable/enable repo, I see webhook POST call worked fine. Do you have any other ideas how to check this? Probably issue is that there are several repos with the same name owned by different members?
![screenshot_20](https://user-images.githubusercontent.com/6439757/83390808-346e8b00-a3fb-11ea-89a6-bd65ec455def.png)

**Comment by rarkins** [comment]
Is the repo a fork?

**Comment by y0zg** [comment]
Nope, but I see similar repo name `catalyst-api`  in different our own gitlab group. Any other ideas what I can check?

**Comment by y0zg** [comment]
It seems MR started triggering with renovate upgrade after probably dummy MR I was created. As I mentioned, we were pushing directly  into this repo  without PRs, probably this was a case
