### ISSUE TITLE
Haven't got a lockfile maintenance PR for a month

### ISSUE THREAD

**Issue by ThibaultVlacich** [renovatebot/app-support#54]
Today I noticed that I haven't got a lockfile maintenance for at least a month.

Here's my Renovate config:
```json
{
  "extends": [
    "config:base",
    ":semanticCommitTypeAll(chore)",
    ":masterIssue"
  ],
  "baseBranches": [
    "develop"
  ],
  "lockFileMaintenance": {
    "enabled": true
  },
  "postUpdateOptions": [
    "yarnDedupeHighest"
  ],
  "rangeStrategy": "pin",
  "docker": {
    "labels": ["dependencies", "docker"]
  },
  "js": {
    "labels": ["dependencies", "javascript"]
  },
  "npm": {
    "commitMessageTopic": "{{prettyDepType}} {{depName}}"
  }
}
```

I'm seeing in the logs: `DEBUG: yarn.lock hasn't changed(branch="renovate/lock-file-maintenance")`, but if I run a `yarn upgrade` on my local computer, there is A LOT of changes.

EDIT: In fact, I'm noticing that I haven't got a lock file maintenance PR in any of my repositories for the last month. I have NodeJS and PHP (Composer) repositories, none of them have received a PR in the last month. I'm getting normal dependencies PR though without any issue.

**Comment by rarkins** [comment]
Please let me know the repository name or a job number so that I can look it up.

**Comment by ThibaultVlacich** [comment]
The repository I noticed the issue (if it is an issue) is `ThibaultVlacich/lucklesslovelocks.com-front`, but it's a private repository.

But I'm also noticing the same issue on [ThibaultVlacich/csv-to-strings](https://github.com/ThibaultVlacich/csv-to-strings/), which is public.

**Comment by rarkins** [comment]
Thanks for the info. I've now identified a problem in our code which is leading to them getting skipped and will patch it today. By default it runs on a schedule of Monday mornings, but you can override that if you prefer. I'll confirm to you once done.

**Comment by rarkins** [comment]
This is now live in the app.

**Comment by ThibaultVlacich** [comment]
I forced the creation of the PR with the master issue and it worked. Thanks
