### ISSUE TITLE
No GitLab onboarding for a fresh setup

### ISSUE THREAD

**Issue by davidwinter** [renovatebot/app-support#55]
**What Renovate type are you using?**

GitLab

**Describe the bug**

From the Renovate dashboard, I enabled my repo and can see that the bot has been added as a Developer, and the webhook added.

On the Renovate dashboard, after refreshing, the repo does not appear anywhere. If I click the settings again, I can see it is enabled for the repo still.

I've not received an Onboarding PR either, and there is no indication in the docs, or anywhere else that I can see setting an expectation if that should be near enough instant, or if you have to wait minutes, hours or days for that to first appear.

**Did you see anything helpful in debug logs?**

Unfortunately, I don't see any Job ID, as it seems the repo is not in a correct setup state?

**To Reproduce**

This was a brand new setup of Renovate on a GitLab repo, so I just followed the instructions.

**Comment by rarkins** [comment]
Onboarding GitLab repos in the app takes up to 2 hours. GitLab has no app interface that lets us get a webhook when we are added to a repo.

The repo list in the UI is based on *logs* so if no run yet then it won't show up.

**Comment by davidwinter** [comment]
Thanks @rarkins - I'll keep an eye out. 

Would it not be possible to trigger the initial onboarding PR after you have added the bot as a Developer member/added the webhook?

**Comment by davidwinter** [comment]
@rarkins it's been more than two hours since I submitted the issue. Is there a scheduled job run every 2hrs for new repos that are added? Should that have run by now? Sorry to sound impatient. 

I'm really keen to start using renovate, and just want to make sure I've done everything right in terms of setup.

**Comment by rarkins** [comment]
What's one of the repo names you're waiting for?

**Comment by davidwinter** [comment]
> What's one of the repo names you're waiting for?

On GitLab, `leavesunderfoot/nimblenote`

**Comment by davidwinter** [comment]
@rarkins unsure if you triggered something, but I just received the onboarding pull request :boom:

**Comment by rarkins** [comment]
It was in the job queue and ran by itself right when I was taking a look. Should be onboarding now, and you should hopefully be able to view logs via the dashboard too

**Comment by davidwinter** [comment]
@rarkins great, thanks so much for looking, really appreciate it. Can confirm it is now also appearing in the dashboard.

I think perhaps if the onboarding PR can be setup as discussed further up, that'd be great for the UX and just remove any initial uncertainty.

Great job with this all btw, it's an amazing tool :+1:

**Comment by rarkins** [comment]
Thanks, yes I agree it would be nice to enqueue a job immediately when the webhook is created.

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
