### ISSUE TITLE
After upgrading to Yarn 2.0.0-rc.36 & PnP, Renovate no longer updates yarn.lock, complains about artifact update problem

### ISSUE THREAD

**Issue by davissorenson** [renovatebot/app-support#59]
I updated Yarn in my project to 2.0.0-rc.36 and started using Plug'n'Play at the same time. Renovate now only updates package.json, and doesn't touch yarn.lock. Also, the "renovate/artifacts" check fails with an "Artifact file update failure" as well as the below comment.

<img width="930" alt="Screen Shot 2020-07-04 at 1 44 53" src="https://user-images.githubusercontent.com/1462923/86500174-fec11700-bd97-11ea-9798-74361a6201e5.png">

My renovate config extends `config:base`, nothing more. The platform is GitHub.

Have I configured Renovate incorrectly, or does Renovate not support Yarn 2 and/or PnP?

Thanks in advance.

**Comment by rarkins** [comment]
Yarn v2 support is still a work in progress. There's an issue in the main repo you can track instead, but I'm on mobile right now so don't have it handy.

**Comment by davissorenson** [comment]
Thanks, that makes sense! I'll link the issue here for anyone coming from Google:
https://github.com/renovatebot/renovate/issues/5230
