### ISSUE TITLE
dashboard does not list enabled repos

### ISSUE THREAD

**Issue by 123Haynes** [renovatebot/app-support#6]
I have renovate enabled for 2 public repositories on gitlab.com.  
It works just fine, but when I access the dashboard under https://renovatebot.com/dashboard  
it doesn't show me the logs for those repos.  
I can verify that it is enabled, but the enabled repos are not listed otherwise.  
See attached screenshot.

![screenshot-renovatebot com-2019 08 20-08_25_29](https://user-images.githubusercontent.com/209302/63322698-57282b00-c324-11e9-834c-d704ac703853.png)

**Comment by 123Haynes** [comment]
In my case the issue seems to be a 502 error when calling the installations endpoint.  
Not sure what the root cause is though 😢 

![502](https://user-images.githubusercontent.com/209302/64480637-684db480-d1cb-11e9-8e7b-747a5dede8fe.png)

**Comment by rarkins** [comment]
@123Haynes Sorry, the dashboard API was actually down temporarily. Can you retry now?

**Comment by 123Haynes** [comment]
@rarkins now I see one of the 2 repos where renovate is enabled.  
`orika-spring-boot-starter` does not show up, despite being enabled for a few months now.

**Comment by rarkins** [comment]
@123Haynes I can confirm that that repo is being run every hour, so I'm not sure why it's not showing up in the list. I'll take a look.

**Comment by rarkins** [comment]
@123Haynes is it showing up now?

**Comment by 123Haynes** [comment]
@rarkins I can't check it at the moment, unfortunately.   
When I try to open https://renovatebot.com/dashboard I see the login screen for about 1 second before being redirected to https://app.renovatebot.com/register  

I managed to click "sign in with gitlab" once and I'm able to authenticate myself, but I'm still being redirected to the registration page 😢 

Since I can't login, I also can't check if the problem is fixed.

**Comment by rarkins** [comment]
Can you try an alternative browser, and let me know in case that makes a difference? And then if not, please let me know what OS/browser it is you're using and if you see any errors in the console logs when you try this?

**Comment by 123Haynes** [comment]
@rarkins I tested this with Windows 10 and the current Chrome.
 I also tested it just now with Ubuntu and Firefox 70.0.1 on a different PC and get the same results.

I've uploaded my network trace here (because github won't let me attach it for some reason):
https://gitlab.com/snippets/1914602
You can extract it and import it in the firefox developer tools to see all network calls.

With Firefox I get these messages in the console:  


```
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://app.renovatebot.com/css/bootstrap.min.css
Source-Map-Adresse: bootstrap.min.css.map

SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:5928
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:6175
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:7418
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:9504
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:9814
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:11621
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:12196
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:12234
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:13241
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:13553
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:15379
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:15676
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:15874
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:16967
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:18732
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:18832
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:18892
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:19090
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:20262
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:21521
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:21632
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:38497
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:38613
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:49046
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:58423
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:59611
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:65222
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:66968
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:67031
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:67338
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:67401
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:67808
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:68088
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:73456
SyntaxError: test for equality (==) mistyped as assignment (=)?
jquery-3.4.1.min.js:2:75054
ReferenceError: reference to undefined property "delegateType"
jquery-3.4.1.min.js:2:40735
ReferenceError: reference to undefined property "focusout"
jquery-3.4.1.min.js:2:32608
ReferenceError: reference to undefined property "nodeType"
jquery-3.4.1.min.js:2:32173
ReferenceError: reference to undefined property "triggered"
jquery-3.4.1.min.js:2:40518
ReferenceError: reference to undefined property "title"
jquery-3.4.1.min.js:2:33908
ReferenceError: reference to undefined property "template"
bootstrap-select.js:2979:10
ReferenceError: reference to undefined property "type"
jquery-3.4.1.min.js:2:43643
ReferenceError: reference to undefined property "triggered"
jquery-3.4.1.min.js:2:69872
ReferenceError: reference to undefined property "result"
jquery-3.4.1.min.js:2:42701
ReferenceError: reference to undefined property "optID"
bootstrap-select.js:1421:14
```

**Comment by rarkins** [comment]
Thanks. None of those errors/warnings appear related to the dashboard code.

Re: the har, all it's showing is that the request to `/user` said you need activation and then you were redirected to the form. I think we'd need at least the next step of form submission -> dashboard redirect -> `/user` request in order to draw any conclusions.

**Comment by 123Haynes** [comment]
@rarkins I see my error now.  
It is just very confusing UX design.  
Apparently I was already logged in so `/dashboard` immediately redirected me to the form to accept the new TOS.  
Unfortunatly this is really confusing, because the endpoint is called `/registration` and the form mentions registration on several places.  

I think this can be improved a lot by changing the wording.  

The form is about accepting the new TOS right?  
So a more fitting endpoint would be `/agreement` or `/activation`.
Also the form is missing any form of explanation why you suddenly need to submit it.


After submitting the form, I'm able to see my dashboard.
`orika-spring-boot-starter` still does not show up. :cry:

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
