### ISSUE TITLE
Logs are unavailable on the dashboard

### ISSUE THREAD

**Issue by at-wat** [renovatebot/app-support#62]
### What Renovate type are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### The problem

On the dashboard page, logs after July 10th, 6 PM (UTC) seems unavailable.
I have checked multiple repositories over multiple GitHub organizations, all repository seems in the same condition.

For example of my public repositoy,
[Job ID 201179148 (Friday, July 10th 2020, 5:28:54 pm UTC)](https://app.renovatebot.com/dashboard#github/at-wat/mqtt-go/201179148) is available. 
![image](https://user-images.githubusercontent.com/8390204/87238890-684dbf00-c443-11ea-89ae-adedeadebcba.png)
But,
[Job ID 201202377 (Friday, July 10th 2020, 6:42:12 pm UTC)](https://app.renovatebot.com/dashboard#github/at-wat/mqtt-go/201202377) is unavailable.
![image](https://user-images.githubusercontent.com/8390204/87238896-769bdb00-c443-11ea-8dee-f96f9977167d.png)

In both case, request to `GET https://v1.renovateapi.com/github/repos/:owner/:repository/jobs/:jobid/logs` seems responded with `200 OK`.

**Comment by rarkins** [comment]
Thank you for raising this. Unfortunately the logs were getting truncated so it was a valid but empty file. It's now fixed and you should see at least one recent working log (201869061) for this repo.

**Comment by at-wat** [comment]
Thank you for fixing it!
