### ISSUE TITLE
renovate uses two identities `renovate[bot]` and `renovate-bot`

### ISSUE THREAD

**Issue by monperrus** [renovatebot/app-support#63]
By looking at the stats of my project https://github.com/INRIA/spoon/pulse

I see that Renovate has two different Github identities:

* `renovate[bot]` 3 commits by https://github.com/renovate[bot]
* `renovate-bot` 2 commits by https://github.com/renovate-bot

What about using a single identity?

**Comment by rarkins** [comment]
Future commits should be by the [bot] account now

**Comment by monperrus** [comment]
Thanks a lot.
