### ISSUE TITLE
Onboarding PR not received if merge requests are disabled and then enabled

### ISSUE THREAD

**Issue by pomma89** [renovatebot/app-support#64]
First of all, two things:

- Thanks for your great product.
- I'm sorry for the following issue, I did not know/remember that merge requests were disabled on target project.

I was trying to active Renovate on this project:

https://gitlab.com/pomma89/object-pool

However, merge requests were disabled and I did not remember that. Obviously, onboarding PR was not open and, by checking the Renovate logs, I found a "disabled" entry.

That entry helped me find my mistake, but, after enabling merge requests, no new logs appeared. I tried "removing" the project using the dashboard but nothing changed. After a few days, also the "disabled" log entry disappeared.

Can you force a new run on your side?

Thanks and I'm sorry for my mistake.

Bye, Alessio

**Comment by rarkins** [comment]
Yes, I can try fixing this on the backend by removing the entry.

**Comment by pomma89** [comment]
> Yes, I can try fixing this on the backend by removing the entry.

Yes, it would be appreciated. Do you need me to do anything on project side?

Thanks, Alessio

**Comment by rarkins** [comment]
I don't anticipate so

**Comment by rarkins** [comment]
Fixed: https://gitlab.com/pomma89/object-pool/-/merge_requests/9

**Comment by pomma89** [comment]
Thank you very much.

Goodbye, Alessio
