### ISSUE TITLE
Renovate hasn't run for 2 days on SEEK-Jobs Org

### ISSUE THREAD

**Issue by etaoins** [renovatebot/app-support#66]
The SEEK-Jobs private GitHub org uses Renovate heavily with 400 repos configured. However, no PRs have been opened for the past 2 days and according to the dashboard no jobs have been run.

**Comment by rarkins** [comment]
Hi, this problem has been resolved and you should have seen all repos run now. Sorry for the inconvenience!

**Comment by etaoins** [comment]
Thanks for the quick turnaround!
