### ISSUE TITLE
Lock file maintenance always outside of schedule

### ISSUE THREAD

**Issue by dword-design** [renovatebot/app-support#67]
**What Renovate type are you using?**

Hosted app GitHub

**Describe the bug**
I have setup Renovate with the default lock file maintenance config:
```js
"lockFileMaintenance": {
    "enabled": true
  }
```
But it seems that before 5am is never executed according to my logs (see below).

**Relevant debug logs**
See https://app.renovatebot.com/dashboard#github/dword-design/base-config-nuxt

**To Reproduce**
See https://app.renovatebot.com/dashboard#github/dword-design/base-config-nuxt
See the renovate config: https://github.com/dword-design/base-config-nuxt/blob/master/.renovaterc.json

**Comment by rarkins** [comment]
Thanks for the confirmation. In that case I'm pretty sure it was an app-specific bug where some repos were not being enqueued. Sorry, but hopefully won't happen again.
