### ISSUE TITLE
Master issue issue (wrong deps listed)

### ISSUE THREAD

**Issue by moltar** [renovatebot/app-support#68]
**What Renovate type are you using?**

Hosted

**Describe the bug**

Renovated opened a master issue in a repo, but the deps it lists are inconsistent with the deps the repo actually uses.

**Relevant debug logs**

Issue here: https://github.com/ScaleLeap/amazon-mws-api-sdk/issues/129

See `package.json` in the repo. ([link](https://github.com/ScaleLeap/amazon-mws-api-sdk/blob/64addea008a1b08de4dcf9d1f9ca23d91b7800d9/package.json#L43-L68))

**To Reproduce**

Not sure how to repro this, but look at the above issue.

**Additional context**

Oddly no other repo has a master issue, only this one.

**Comment by rarkins** [comment]
Unfortunately Renovate had a glitch and listed some of its *own* deps in that master issue. It should not happen again and please feel free to close or delete the erroneous issue.

**Comment by moltar** [comment]
@rarkins Thanks for the explanation.

I think Renovate should have followed up with an issue comment explaining that.
