### ISSUE TITLE
Getting PRs as soon as possible

### ISSUE THREAD

**Issue by simoneb** [renovatebot/app-support#7]
### Which Renovate are you using? CLI, App, or Pro

App

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps

GitHub

### What is your question?

We are using Renovate to bump internal package versions and we would need it to do it as timely as possible after a package is released.

We're not watching closely how long on average it takes, but we've seen some cases when getting a PR from Renovate was very slow. There was one case where a PR for bumping a package version happened at 10:51AM MDT (can't tell exactly when the package was published to our private registry but I imagine a few minutes later), but we didn't receive a renovate PR until 5:31PM MDT, so hours later.

For internal packages we're using the "at any time" schedule.

**Comment by simoneb** [comment]
Ok I understand, thanks for the clarifications. Is there a way for us to get those PRs more quickly? Just for our internal packages.

Here's the (redacted) configuration:

```
{
  "extends": ["config:base"],
  "statusCheckVerify": true,
  "ignoreDeps": [redacted],
  "schedule": ["every weekend"],
  "labels": ["renovate"],
  "packageRules": [
    {
      "packageNames": [redacted], <-- this is one of our internal packages for which we'd want timely PRs
      "groupName": redacted,
      "assignees": [
        redacted
      ],
      "schedule": ["at any time"]
    }
  ],
  "vulnerabilityAlerts": {
    "labels": ["SECURITY"]
  },
  "encrypted": {
    "npmToken": redacted
  },
  "npmrc": redacted
}
```

**Comment by rarkins** [comment]
I just pushed a new feature to the app. If you add `"masterIssue": true` to your config then you'll get a mini-dashboard "Master Issue" added to your repo. Down the bottom is an "Advanced" section which lets you tick a box to request a new run on your repo at any time. So in cases where you're impatient for an update, ticking this box should put your repository to the front of the queue and speed it up.

![image](https://user-images.githubusercontent.com/6311784/63648407-a8268d80-c72f-11e9-9a82-014f03d21db5.png)
