### ISSUE TITLE
Dashboard: only 100 repositories loaded from GitLab

### ISSUE THREAD

**Issue by mbrodala** [renovatebot/app-support#74]
**What Renovate type are you using?**

I'm using the hosted app on https://app.renovatebot.com/dashboard with GitLab.com (hosted)

**Describe the bug**

The wizard for adding repositories only loads 100 repositories from GitLab.

**Relevant debug logs**

I can see the following requests in the XHR section of the browser network pane:

- `https://gitlab.com/api/v4/projects?archived=false&min_access_level=40&per_page=100`
- `https://gitlab.com/api/v4/groups/<my-group>`
- 100 times `https://gitlab.com/api/v4/projects/<project-id>/members` with a 404 response

**To Reproduce**

Open the wizard from the dashboard with a GitLab.com account having access to more than 100 repositories.

**Additional context**

I can see that there *should* be pagination support (#972)

**Comment by rarkins** [comment]
Pagination should now be working for GitLab when you select the install option. Please comment here once you can test it to confirm it's fixed or reopen the issue

**Comment by mbrodala** [comment]
Thanks, I can confirm that now all projects are loaded from GitLab. :-)
