### ISSUE TITLE
Gitlab App stuck after 'no package files'

### ISSUE THREAD

**Issue by j0nm1** [renovatebot/app-support#75]
**What Renovate type are you using?**

I'm using the Gitlab App (https://app.renovatebot.com/dashboard) and Gitlab.com

**Describe the bug**

The Repository only was checked once (when it was empty) and now (after I added some dependencies) Renovate does not seem to run anymore. It didn't create an onboarding Merge Request, so I simply copied my config from another project. But there are no new jobs visible in the Dashboard.

**Relevant debug logs**

The only Job ID I have is 219848987. 

**To Reproduce**

**Additional context**

The project is located in a subgroup: `gitlab.com/group/subgroup/repo`

**Comment by rarkins** [comment]
I've removed the "disabled" status from this repo in the backend so it should be picked up in the next 1-2 hours

**Comment by j0nm1** [comment]
Thank you! I will close this issue when I see the first job.

Edit: It works!
