### ISSUE TITLE
[Dashboard] Running job indicator

### ISSUE THREAD

**Issue by viceice** [renovatebot/app-support#79]
It would be nice to have an indicator on the repo job list, which shows if  renovate is currently running on the repo

**Comment by rarkins** [comment]
But challenging. Needs either a pub/sub interface added or to risk polling the DB too often

**Comment by viceice** [comment]
as a start it would be enough to update inidcator when fetching jobs, so no live update 🙃

**Comment by rarkins** [comment]
Yes, we could maybe do a join for that query

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
