### ISSUE TITLE
My dashboard is giving me a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by 9ntonio** [renovatebot/app-support#8]
### Which Renovate are you using? CLI, App, or Pro
I'm using the github app.

### Which platform are you using? GitHub, GitLab, Bitbucket Azure DevOps
GitHub

I am trying to get into my dashboard to see why I am not getting an initial PR for my repo. When I look at the console I am getting the following:

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)

dashboard.js:67 Unauthorized

(anonymous) @ dashboard.js:67

dashboard.js:412 Uncaught (in promise) Unauthorized
v1.renovateapi.com/github/repos/9ntonio/chatcat-server/jobs:1 Failed to load resource: the server responded with a status of 401 ()
```

How do I give the app github authorization when I do see it is not listed. I'm assuming this is the cause of the error above.

Thanks.

**Comment by rarkins** [comment]
Can you take screenshots prior to there? Eg directly after you log in? I want to see if anything loads and  what api calls fail

**Comment by 9ntonio** [comment]
<img width="1792" alt="Screen Shot 2019-09-09 at 9 56 32 AM" src="https://user-images.githubusercontent.com/2566895/64550667-3ed67b00-d2e8-11e9-83c0-6e5b0a60a266.png">
<img width="1792" alt="Screen Shot 2019-09-09 at 9 56 44 AM" src="https://user-images.githubusercontent.com/2566895/64550668-3ed67b00-d2e8-11e9-9df3-887bd8d11f6a.png">

I was able to log off then log back in. I noticed that I needed to authorize the bot again for it to let me into the dashboard. After I was in I see the following issues across multiple repos. Is this an issue of bot authentication?

**Comment by rarkins** [comment]
That was unfortunately a system-wise bug earlier today. Do you have any subsequent logs for each repo?

**Comment by 9ntonio** [comment]
After reviewing the logs for my repo's, I see that I do have the initial configuration PR for all except this one - https://github.com/9ntonio/portfolio/

Here is the log:

<img width="1792" alt="Screen Shot 2019-09-09 at 10 35 37 AM" src="https://user-images.githubusercontent.com/2566895/64553121-a80cbd00-d2ed-11e9-8aeb-318632ee0bf8.png">

**Comment by 9ntonio** [comment]
Do I need to reset the bot in order to have the repo above begin to create an initial PR?

**Comment by rarkins** [comment]
You will need to add a `renovate.json` manually for 9ntonio/portfolio and be sure to include the config `"includeForks": true`. Renovate skips forks whenever you have installed Renovate into "all repositories" because in the majority of cases users don't intend for forks to be covered by Renovate.

**Comment by 9ntonio** [comment]
Thank you! That makes complete sense. I'll install per your instruction s and see if it addresses my issue. If it does I will close this ticket out.

**Comment by 9ntonio** [comment]
Hello, I have another question. I've added the renovate.json file to my project - https://github.com/9ntonio/portfolio/blob/develop/renovate.json

Yet I am not seeing any actions for this repo when I go to my dashboard. My goal is to get the bot to see the settings and begin to create PR's, but I am not seeing any interactions. I assume I am missing something in the set up for this goal to work?

**Comment by 9ntonio** [comment]
Bumping in hopes I can receive some feedback. Thanks.

**Comment by rarkins** [comment]
I gave it a bump just now and it ran, but didn't create PRs due to the schedule. Should hopefully create PRs the next time it's within schedule.

**Comment by 9ntonio** [comment]
Thank you!

**Comment by 9ntonio** [comment]
Thanks again for your help. The bot is working again as you said previously. I appreciate the help and time.
