### ISSUE TITLE
Adding new repos broken existing repos

### ISSUE THREAD

**Issue by james-simpson-ST** [renovatebot/app-support#80]
### Which Renovate are you using?
WhiteSource Renovate App

### Which platform are you using?
GitLab.com 

### Have you checked the logs? Don't forget to include them if relevant
Logs are no longer updating since 1 day ago

### What would you like to do?
Yesterday I tried to board 4 new repos from the trustpayments-public GitLab group, however, we already have some private repos in another GitLab group. Since adding these repos I have not received any Onboarding MRs on the public repos and we no longer seem to get logs to show that the old repos are still working. I'm not sure if adding these new repos from a different GitLab group has somehow not worked and also broken the other integrations or if it's just the dashboard isn't displaying the logs anymore.

I have tried removing the repos from trustpayments-public but the other private repos still don't get updated logs and then when re-adding the trustpayments-public we still don't receive the onboarding MRs

**Comment by rarkins** [comment]
The four repos from trustpayments-public all seem to be installed correctly, e.g. https://gitlab.com/trustpayments-public/stjs/js-payments/-/merge_requests/48

**Comment by james-simpson-ST** [comment]
Thank you for replying, this sprang into life after about 48hrs thank you for checking this
