### ISSUE TITLE
npm audit fix

### ISSUE THREAD

**Issue by broksonic21** [renovatebot/app-support#82]
With npm turned on, we see our package.json get bumped, but that often still leaves npm audit warnings in the package-lock.json 

Is there a way to get the equivalent of `npm audit fix` to automatically run?

or is that because we don't have package-lock.json listed here in includePaths?

  "automerge": true,
  "rangeStrategy": "bump",
  "enabledManagers": ["npm"],
  "includePaths": ["package.json"],

**Comment by rarkins** [comment]
Sorry, that's not functionality we support, although if running on GitHub then we do attempt to reuse their vulnerability alerts. Adding `package-lock.json` won't work, and actually your `includePaths` isn't necessary either.
