### ISSUE TITLE
Use custom gitlab token

### ISSUE THREAD

**Issue by sesigl** [renovatebot/app-support#84]
Hey there,

first of all, thanks for this great as a service renovate bot!

I am using vercel (ex. zeit.co) cloud where you pay by user. A user is about $20 per month that is very much for my little project to pay. Is it possible to just use my person github account + token to do commits, create merge request and so on?

Would be awesome if I could just set it in my renovate.json, but I didn't find any documentation about it.

Thanks in advance!

**Comment by rarkins** [comment]
How is a user determined? e.g. git author or git committer?

**Comment by rarkins** [comment]
Looks like git author? https://vercel.com/docs/git-integrations#deploying-private-git-repositories

If so then we can customize that for you (manually, not through config)

**Comment by sesigl** [comment]
Yes, indeed

They use the commit author. Can you set it up for me?

I think they are using an email address as the main ID if I am not mistaken.

Would be awesome if you can just set mine :).

akrillo89 at gmail.com

Thanks in advance! I will doubt check if it works.

Would be awesome for the future if it could be configurable somehow :).

**Comment by rarkins** [comment]
What's your GitLab username or group?

**Comment by sesigl** [comment]
https://gitlab.com/Journerist

**Comment by rarkins** [comment]
I've attempted to tweak it on the backend. The next time you get an MR - or perhaps rename/close an existing one - it should hopefully have your own gitAuthor set

**Comment by sesigl** [comment]
Hey, unfortunately, it's blocked again. Can we also set the git author email to my mail? I also know they are trying to implement some improvements on their side.

**Comment by rarkins** [comment]
The gitAuthor value has already been set for your account

**Comment by sesigl** [comment]
Interesting,

I thought the information should be visible in: 
https://app.renovatebot.com/dashboard#gitlab/Journerist/explore-the-world-frontend/233930865

there I still see

```
DEBUG: git clone completed
{
  "durationMs": 54481
}
DEBUG: latest commit
{
  "latestCommitDate": "2020-09-20T20:02:04+00:00"
}
DEBUG: Setting git author name
{
  "gitAuthorName": "Renovate Bot"
}
DEBUG: Setting git author email
{
  "gitAuthorEmail": "bot@renovateapp.com"
}
```

**Comment by rarkins** [comment]
Actually you're right, I hadn't configured it correctly. Pushing a fix now, should be active in the next few minutes for any commits that happen *after*.

**Comment by akrillo89** [comment]
Hey,

I got in contact with the vercel folks. They adjusted a few things and now it should work out of the box. Can you revert all override/changes to my account?

Thank you! :) 

All the best

**Comment by sesigl** [comment]
I talked to the renovate folks and they adjusted a few things. Now, it should work out of the box. Can you revert all overrides/changes that are specific to my account?

Thanks in advance!

**Comment by rarkins** [comment]
Done
