### ISSUE TITLE
No projects shown in Dashboard for GitLab

### ISSUE THREAD

**Issue by remal** [renovatebot/app-support#87]
**What Renovate type are you using?**

Renovate through the renovate-bot on GitLab.com.

**Describe the bug**

1. I logged into the Renovate Dashboard (https://app.renovatebot.com/dashboard) using GitLab for authorization.
1. Then I enabled Renovate for my [project](https://gitlab.com/remal/name.remal.gradle-api-artifacts/).
1. However, the list of projects remains empty. Pressing `Ctrl+F5` doesn't help

**Expected behavior**

I was expecting to see my [project](https://gitlab.com/remal/name.remal.gradle-api-artifacts/) in the list.

**Comment by rarkins** [comment]
The left sidebar is populated based on logs, so unfortunately at the very beginning it can be confusingly absent until the first job is run. You should see that a couple of jobs have run already, although there are no updates detected so no MRs.
