### ISSUE TITLE
[Dashboard] Not seeing the repos from organisation on dashboard

### ISSUE THREAD

**Issue by onkartibe** [renovatebot/app-support#88]
I have authenticated and given access to github repos which are under private organisation. I dont see any repos under my dashboard. 

Is there any issues any one facing?  

![Screen Shot 2020-09-23 at 12 06 31 PM](https://user-images.githubusercontent.com/5966412/93949660-52d70880-fd95-11ea-8b77-e42da0f9ac9c.png)

**Comment by rarkins** [comment]
The dashboard shows repos that:

1. Have been installed into Renovate using https://github.com/apps/renovate
2. You have write access to

So most likely you or an org admin need to first install the app

**Comment by rarkins** [comment]
I'm going to archive this repository so that we have conversations in one place. Therefore please create an "App Support" discussion here if this problem or suggestion is still relevant: https://github.com/renovatebot/renovate/discussions
