### ISSUE TITLE
[App Dashboard] missing json metadata html encoding

### ISSUE THREAD

**Issue by viceice** [renovatebot/app-support#89]
json objects are not html encoded, so

`"// renovate: datasource=(?<datasource>[a-z-]+?) depName=(?<depName>.+?)(?: versioning=(?<versioning>[a-z-]+?))?\\s+readonly\\s+tag\\s+=\\s+'(?<currentValue>.+?)';"`

gets visible to:

 ` "// renovate: datasource=(?[a-z-]+?) depName=(?.+?)(?: versioning=(?[a-z-]+?))?\\s+readonly\\s+tag\\s+=\\s+'(?.+?)';"`

named regex capture groups are interpreted as html

![image](https://user-images.githubusercontent.com/1798109/94902591-ba2d4080-0498-11eb-822b-7e42da853107.png)

**Comment by rarkins** [comment]
I think it's now fixed:

![image](https://user-images.githubusercontent.com/6311784/94910008-5872d380-04a4-11eb-8fb8-9cbdad5a13b8.png)
