### ISSUE TITLE
Renovate bot stopped all PRs to one repo

### ISSUE THREAD

**Issue by internettrans** [renovatebot/app-support#91]
This repository has not received a renovate bot PR since June, and I'm not sure why. Any insight or help is appreciated:

https://github.com/esm-bundle/react

**Comment by rarkins** [comment]
If I check the logs manually, it has been running a few times in the past days, including one manual one I triggered when seeing this issue:

![image](https://user-images.githubusercontent.com/6311784/97071071-d7f44e00-15dd-11eb-858e-6b1e51fb9ab9.png)

If you log into app.renovatebot.com you can see the log and notice there are no updates pending:

```json
{
  "level": 20,
  "config": {
    "npm": [
      {
        "packageFile": "package.json",
        "deps": [
          {
            "depType": "devDependencies",
            "depName": "@rollup/plugin-replace",
            "currentValue": "2.3.3",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "2.3.3",
            "depIndex": 0,
            "warnings": [],
            "fixedVersion": "2.3.3",
            "sourceUrl": "https://github.com/rollup/plugins",
            "updates": []
          },
          {
            "depType": "devDependencies",
            "depName": "esm-bundle-scripts",
            "currentValue": "1.2.0",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "1.2.0",
            "depIndex": 1,
            "warnings": [],
            "fixedVersion": "1.2.0",
            "sourceUrl": "https://github.com/esm-bundle/esm-bundle-scripts",
            "updates": []
          },
          {
            "depType": "devDependencies",
            "depName": "react",
            "currentValue": "17.0.1",
            "datasource": "npm",
            "prettyDepType": "devDependency",
            "lockedVersion": "17.0.1",
            "depIndex": 2,
            "warnings": [],
            "fixedVersion": "17.0.1",
            "sourceUrl": "https://github.com/facebook/react",
            "sourceDirectory": "packages/react",
            "homepage": "https://reactjs.org/",
            "updates": []
          }
        ],
        "packageJsonName": "@esm-bundle/react",
        "packageFileVersion": "17.0.1",
        "packageJsonType": "library",
        "yarnLock": "yarn.lock",
        "skipInstalls": true,
        "constraints": {}
      }
    ],
    "nvm": [
      {
        "packageFile": ".nvmrc",
        "manager": "nvm",
        "deps": [
          {
            "depName": "node",
            "currentValue": "node",
            "datasource": "github-tags",
            "lookupName": "nodejs/node",
            "depIndex": 0,
            "warnings": [],
            "skipReason": "unsupported-value",
            "updates": []
          }
        ]
      }
    ],
    "travis": [
      {
        "packageFile": ".travis.yml",
        "manager": "travis",
        "deps": [
          {
            "depName": "node",
            "currentValue": [
              "node"
            ],
            "depIndex": 0,
            "updates": []
          }
        ]
      }
    ]
  },
  "msg": "packageFiles with updates",
  "time": "2020-10-24T07:44:21.642Z"
}
```

Please close if you feel this is resolved

**Comment by internettrans** [comment]
Hi @rarkins, thanks for your response. The esm-bundle/react repo has not received a PR from renovate bot since june - see https://github.com/esm-bundle/react/pulls?q=is%3Apr+is%3Aclosed. Notably it depends on `react` which has had several updates since June, including the recent update to 17.0.0 and 17.0.1. I have had to manually upgrade the dependency every time a new version of React is released.

If you compare the PRs for esm-bundle/react to esm-bundle/react-dom, you'll see the difference between a repository that is working properly versus one that is not:

https://github.com/esm-bundle/react/pulls?q=is%3Apr+is%3Aclosed
https://github.com/esm-bundle/react-dom/pulls?q=is%3Apr+is%3Aclosed

**Comment by rarkins** [comment]
Repositories with no commits for a month get marked as stale and no longer checked automatically. This is maybe what happened. There's nothing to look at right now if there are no updates pending.

**Comment by internettrans** [comment]
I see - I didn't know that about staleness. Thanks for your help

**Comment by rarkins** [comment]
Yeah, it's kind of a backend optimization, we aim to re-check everything once per week just in case but it doesn't always happen.

FYI if you enable `dependencyDashboard` then it gives you an option to tick a checkbox and request a job run on demand, which would work in such cases.
