### ISSUE TITLE
Renovate isn't running on some repos

### ISSUE THREAD

**Issue by mcbanderson** [renovatebot/app-support#94]
### Which Renovate are you using?

WhiteSource Renovate App

### Which platform are you using?

GitHub.com

### Have you checked the logs? Don't forget to include them if relevant

There are no logs to check because Renovate seems to not be running as expected.

### What would you like to do?

Renovate doesn't seem to be running as I expect. Not sure if this is a configuration issue, a bug, or perhaps some kind of rate limiting.

I have a few dozen repos that all utilize a dependency I manage. That dependency had a new release last night, but Renovate has only opened a PR to update one of the repos. All the repos use the same configuration file.

Configuration file: https://github.com/reflexivesecurity/renovate-config/blob/master/rules.json
Repo that received update PR: https://github.com/reflexivesecurity/reflex-aws-s3-logging-not-enabled/pull/77
Example repo that didn't get a PR: https://github.com/reflexivesecurity/reflex-aws-cloudfront-viewer-tls-protocol/pulls

The repo that received the PR has logs that look as expected. The repos that didn't receive a PR have no recent logs, making it appear as though Renovate hasn't run. For the example repo with no PR the most recent logs are two days old.

I appreciate any help or guidance with this issue.

**Comment by rarkins** [comment]
A couple of your repos are marked as "stale" (no commits for least two weeks), which means they fall out of the regular schedule and get checked usually around once per week. I've manually removed that stale flag for now so you should see them getting serviced within the next ~2 hours. 

If you enable `dependencyDashboard` in onboarded repos then the issue it creates includes a checkbox you can use to request a job on-demand in similar situations.

FYI most of your repos are marked as "onboarding" so they also don't get checked frequently for similar reasons.

**Comment by mcbanderson** [comment]
Thanks for the quick response! That makes sense, I will utilize the `dependencyDashboard` when needed going forward.

**Comment by mcbanderson** [comment]
For anyone who might stumble on this in the future, I was also able to jumpstart the process by running Renovate from the command line:

```
npm install -g renovate
export RENOVATE_TOKEN=<GITHUB_PAT>
renovate --autodiscover
```

This did result in some duplicates of the dependency dashboard issue being created (one from my local run, one from the Renovate app), but for me that was better than waiting for the next scan or bugging the Renovate team
