### ISSUE TITLE
Automerge enabled PRs not merging

### ISSUE THREAD

**Issue by mattkgwhite** [renovatebot/app-support#96]
https://github.com/krangence/hacksm/pulls

Several PRs which are automerge enabled are not automerging

No branch protection rules are set and no other errors shown.

Force retry seems to trigger a force push just fine, but no merge.

**Comment by rarkins** [comment]
For safety reasons, Renovate won't automerge branches that are missing tests. To enable automerging untested branches, add `"requiredStatusChecks": null` to your config.

To request re-runs on demand, I recommend you use this option in your Dependency Dashboard:
![image](https://user-images.githubusercontent.com/6311784/98461536-26444800-21ad-11eb-85f9-5ef05dad55b1.png)

Clicking this simply asks Renovate to run again, and doesn't force any rebase
