### ISSUE TITLE
"No space left on device" on a job

### ISSUE THREAD

**Issue by sylvestre** [renovatebot/app-support#98]
Trying renovate in Firefox, the build job are failing because of "No space left on device" during the clone task

Job: 259017229

**Comment by rarkins** [comment]
It's running now but looking like it might exceed our typical ~30 minute timeout and get killed before it finishes. I'll need to look into if we can make an exception to that too in an elegant way

**Comment by sylvestre** [comment]
Not sure it is the same but https://github.com/mozilla/gecko-dev/pull/531 worked a few weeks ago :)

**Comment by rarkins** [comment]
Looks like it finished after all. We default to an SSD with about 3.5GB of space but when I notice repos getting errored we switch them to EBS which can go up to about 20GB. Any particular reason you needed to install on your fork?
